/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeRouteImport } from './routes/employe'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeIndexRouteImport } from './routes/employe/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EmployeProductionRouteImport } from './routes/employe/production'
import { Route as EmployePaymentsRouteImport } from './routes/employe/payments'
import { Route as EmployeNotificationsRouteImport } from './routes/employe/notifications'
import { Route as EmployeMessagesRouteImport } from './routes/employe/messages'
import { Route as EmployeMapRouteImport } from './routes/employe/map'
import { Route as EmployeFarmersRouteImport } from './routes/employe/farmers'
import { Route as EmployeDeliveriesRouteImport } from './routes/employe/deliveries'
import { Route as EmployeCalendarRouteImport } from './routes/employe/calendar'
import { Route as EmployeAiRouteImport } from './routes/employe/ai'
import { Route as AuthSelectRoleRouteImport } from './routes/auth/select-role'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminProductionRouteImport } from './routes/admin/production'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDeliveriesRouteImport } from './routes/admin/deliveries'

const EmployeRoute = EmployeRouteImport.update({
  id: '/employe',
  path: '/employe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeIndexRoute = EmployeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeProductionRoute = EmployeProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployePaymentsRoute = EmployePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeNotificationsRoute = EmployeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeMessagesRoute = EmployeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeMapRoute = EmployeMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeFarmersRoute = EmployeFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeDeliveriesRoute = EmployeDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeCalendarRoute = EmployeCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => EmployeRoute,
} as any)
const EmployeAiRoute = EmployeAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => EmployeRoute,
} as any)
const AuthSelectRoleRoute = AuthSelectRoleRouteImport.update({
  id: '/auth/select-role',
  path: '/auth/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductionRoute = AdminProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRoute
  '/employe': typeof EmployeRouteWithChildren
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/employe/ai': typeof EmployeAiRoute
  '/employe/calendar': typeof EmployeCalendarRoute
  '/employe/deliveries': typeof EmployeDeliveriesRoute
  '/employe/farmers': typeof EmployeFarmersRoute
  '/employe/map': typeof EmployeMapRoute
  '/employe/messages': typeof EmployeMessagesRoute
  '/employe/notifications': typeof EmployeNotificationsRoute
  '/employe/payments': typeof EmployePaymentsRoute
  '/employe/production': typeof EmployeProductionRoute
  '/admin/': typeof AdminIndexRoute
  '/employe/': typeof EmployeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/employe/ai': typeof EmployeAiRoute
  '/employe/calendar': typeof EmployeCalendarRoute
  '/employe/deliveries': typeof EmployeDeliveriesRoute
  '/employe/farmers': typeof EmployeFarmersRoute
  '/employe/map': typeof EmployeMapRoute
  '/employe/messages': typeof EmployeMessagesRoute
  '/employe/notifications': typeof EmployeNotificationsRoute
  '/employe/payments': typeof EmployePaymentsRoute
  '/employe/production': typeof EmployeProductionRoute
  '/admin': typeof AdminIndexRoute
  '/employe': typeof EmployeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRoute
  '/employe': typeof EmployeRouteWithChildren
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/employe/ai': typeof EmployeAiRoute
  '/employe/calendar': typeof EmployeCalendarRoute
  '/employe/deliveries': typeof EmployeDeliveriesRoute
  '/employe/farmers': typeof EmployeFarmersRoute
  '/employe/map': typeof EmployeMapRoute
  '/employe/messages': typeof EmployeMessagesRoute
  '/employe/notifications': typeof EmployeNotificationsRoute
  '/employe/payments': typeof EmployePaymentsRoute
  '/employe/production': typeof EmployeProductionRoute
  '/admin/': typeof AdminIndexRoute
  '/employe/': typeof EmployeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/employe'
    | '/admin/deliveries'
    | '/admin/employees'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/security'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-role'
    | '/employe/ai'
    | '/employe/calendar'
    | '/employe/deliveries'
    | '/employe/farmers'
    | '/employe/map'
    | '/employe/messages'
    | '/employe/notifications'
    | '/employe/payments'
    | '/employe/production'
    | '/admin/'
    | '/employe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/admin/deliveries'
    | '/admin/employees'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/security'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-role'
    | '/employe/ai'
    | '/employe/calendar'
    | '/employe/deliveries'
    | '/employe/farmers'
    | '/employe/map'
    | '/employe/messages'
    | '/employe/notifications'
    | '/employe/payments'
    | '/employe/production'
    | '/admin'
    | '/employe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/employe'
    | '/admin/deliveries'
    | '/admin/employees'
    | '/admin/logs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/production'
    | '/admin/security'
    | '/admin/users'
    | '/auth/login'
    | '/auth/register'
    | '/auth/select-role'
    | '/employe/ai'
    | '/employe/calendar'
    | '/employe/deliveries'
    | '/employe/farmers'
    | '/employe/map'
    | '/employe/messages'
    | '/employe/notifications'
    | '/employe/payments'
    | '/employe/production'
    | '/admin/'
    | '/employe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRoute
  EmployeRoute: typeof EmployeRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSelectRoleRoute: typeof AuthSelectRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employe': {
      id: '/employe'
      path: '/employe'
      fullPath: '/employe'
      preLoaderRoute: typeof EmployeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employe/': {
      id: '/employe/'
      path: '/'
      fullPath: '/employe/'
      preLoaderRoute: typeof EmployeIndexRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employe/production': {
      id: '/employe/production'
      path: '/production'
      fullPath: '/employe/production'
      preLoaderRoute: typeof EmployeProductionRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/payments': {
      id: '/employe/payments'
      path: '/payments'
      fullPath: '/employe/payments'
      preLoaderRoute: typeof EmployePaymentsRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/notifications': {
      id: '/employe/notifications'
      path: '/notifications'
      fullPath: '/employe/notifications'
      preLoaderRoute: typeof EmployeNotificationsRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/messages': {
      id: '/employe/messages'
      path: '/messages'
      fullPath: '/employe/messages'
      preLoaderRoute: typeof EmployeMessagesRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/map': {
      id: '/employe/map'
      path: '/map'
      fullPath: '/employe/map'
      preLoaderRoute: typeof EmployeMapRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/farmers': {
      id: '/employe/farmers'
      path: '/farmers'
      fullPath: '/employe/farmers'
      preLoaderRoute: typeof EmployeFarmersRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/deliveries': {
      id: '/employe/deliveries'
      path: '/deliveries'
      fullPath: '/employe/deliveries'
      preLoaderRoute: typeof EmployeDeliveriesRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/calendar': {
      id: '/employe/calendar'
      path: '/calendar'
      fullPath: '/employe/calendar'
      preLoaderRoute: typeof EmployeCalendarRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/employe/ai': {
      id: '/employe/ai'
      path: '/ai'
      fullPath: '/employe/ai'
      preLoaderRoute: typeof EmployeAiRouteImport
      parentRoute: typeof EmployeRoute
    }
    '/auth/select-role': {
      id: '/auth/select-role'
      path: '/auth/select-role'
      fullPath: '/auth/select-role'
      preLoaderRoute: typeof AuthSelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/production': {
      id: '/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AdminProductionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductionRoute: typeof AdminProductionRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductionRoute: AdminProductionRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeRouteChildren {
  EmployeAiRoute: typeof EmployeAiRoute
  EmployeCalendarRoute: typeof EmployeCalendarRoute
  EmployeDeliveriesRoute: typeof EmployeDeliveriesRoute
  EmployeFarmersRoute: typeof EmployeFarmersRoute
  EmployeMapRoute: typeof EmployeMapRoute
  EmployeMessagesRoute: typeof EmployeMessagesRoute
  EmployeNotificationsRoute: typeof EmployeNotificationsRoute
  EmployePaymentsRoute: typeof EmployePaymentsRoute
  EmployeProductionRoute: typeof EmployeProductionRoute
  EmployeIndexRoute: typeof EmployeIndexRoute
}

const EmployeRouteChildren: EmployeRouteChildren = {
  EmployeAiRoute: EmployeAiRoute,
  EmployeCalendarRoute: EmployeCalendarRoute,
  EmployeDeliveriesRoute: EmployeDeliveriesRoute,
  EmployeFarmersRoute: EmployeFarmersRoute,
  EmployeMapRoute: EmployeMapRoute,
  EmployeMessagesRoute: EmployeMessagesRoute,
  EmployeNotificationsRoute: EmployeNotificationsRoute,
  EmployePaymentsRoute: EmployePaymentsRoute,
  EmployeProductionRoute: EmployeProductionRoute,
  EmployeIndexRoute: EmployeIndexRoute,
}

const EmployeRouteWithChildren =
  EmployeRoute._addFileChildren(EmployeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRoute,
  EmployeRoute: EmployeRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSelectRoleRoute: AuthSelectRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
